apiVersion: v1
kind: PersistentVolumeClaim 
#{{- if .Values.metaMaterial.enabled }}
metadata:
  {{ .Values.identifier | toYaml | indent 2 | trim }}
#{{- end }}
  labels:
    app: {{ .Values.metaMaterial.mysqlappname }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysqlstorage | toYaml | trim }}
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: { .Values.mysqlmetaname | toYaml | trim }}
  labels:
    app: {{ .Values.mysqlappname | toYaml | trim }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysqlappname | toYaml | trim }}
      tier: {{ .Values.mysqltier | toYaml | trim }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlappname | toYaml | trim }}
        tier: {{ .Values.mysqltier | toYaml | trim }}
    spec:
      containers:
      - image: {{ .Values.mysqlimage | toYaml | trim }}
        name: {{ .Values.mysqltier | toYaml | trim }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.Secret.secretname | toYaml | trim }}
              key: {{ .Values.Secret.mysqlpass | toYaml | trim }}
        ports:
        - containerPort: 3306
          name: {{ .Values.mysqltier | toYaml | trim }}
        volumeMounts:
        - name: {{ .Values.mysqlmountname | toYaml | trim }}
          mountPath: {{ .Values.mysqlpath | toYaml | trim }} 
      volumes:
      - name: {{ .Values.mysqlmountname | toYaml | trim }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvncame | toYaml | trim }}
