apiVersion: v1
kind: Service
{{- if .Values.metaMaterial.enabled }}
metadata:
  name: {{ .Values.frontend.appname }}
  labels:
    app: {{ .Values.frontend.appname }}
{{- else }}
metadata:
  name: wordpress
  labels:
    app: wordpress
{{- end }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Values.frontend.appname }}
    tier: frontend
  {{ if .Values.public.enabled }}
  type: LoadBalancer
  {{ else }}
  type: NodePort
  {{ end }}
