{{- if .Values.ingress.enabled -}}
{{- $fullName := include "wordpress.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.frontend.appname }}-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.hostname.dnsname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.frontend.appname }}
              servicePort: {{ $svcPort }}
            path: /  
{{- end }}
