{{- if .Values.pvrequired.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.identifier.pvncame | toYaml }}
  labels:
    app: {{ .Values.identifier.webtier | toYaml }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.identifier.dbstorage | toYaml }}
{{- end }}
