apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.identifier.name | toYaml }}
  labels:
    app: {{ .Values.identifier.mysqlappname | toYaml }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Values.identifier.mysqlappname | toYaml }}
    tier: {{ .Values.identifier.dbtier | toYaml }}
  clusterIP: None
